# Generated by Django 2.2 on 2019-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.IntegerField(choices=[(0, 'middle_school'), (1, 'high_school'), (2, 'college'), (3, 'master'), (4, 'phd')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marriage_status',
            field=models.IntegerField(choices=[(0, 'single'), (1, 'bfgf'), (2, 'married'), (3, 'divorced'), (4, 'widow')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex_acceptance',
            field=models.IntegerField(choices=[(0, 'regular'), (1, 'rare'), (2, 'never')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'activated'), (2, 'blocked'), (3, 'deleted')], default=0),
        ),
    ]
