class UserConstants:

    # status
    USER_STATUS_CREATED = 0
    USER_STATUS_ACTIVATED = 1
    USER_STATUS_BLOCKED = 2

    #gender
    USER_GENDER_FEMALE= 0
    USER_GENDER_MALE = 1

    #sex_acceptance
    USER_SEX_ACCEPTANCE_NO = 0
    USER_SEX_ACCEPTANCE_RARE = 1
    USER_SEX_ACCEPTANCE_REGULAR = 2

    #marriage_status
    USER_MARRIAGE_SINGLE = 0
    USER_MARRIAGE_BFGB = 1
    USER_MARRIAGE_MARRIED = 2
    USER_MARRIAGE_DIVORCED = 3
    USER_MARRIAGE_WIDOW = 4

    #education
    USER_EDUCATION_MIDDLE_SCHOOL_AND_BELOW = 0
    USER_EDUCATION_HIGH_SCHOOL = 1
    USER_EDUCATION_COLLEGE = 2
    USER_EDUCATION_MASTER = 3
    USER_EDUCATION_PHD = 4